name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js environment
      uses: actions/setup-node@v6.0.0
      with:
        node-version: 24
        cache-dependency-path: checkers-game/package-lock.json

    - name: Install dependencies
      run: |
        cd checkers-game
        npm install

#    - name: Run Tests
#      run: |
#        cd frontend/web
#        npm test
# we're not ready for testing yet
      
    - name: Build release
      run: |
        cd checkers-game
        npm run build
